### PR TITLE
configwindow.ui default/start tab set to "settings"

### PR DESCRIPTION
**Pull request by jounathaen**
The settings tab is the first in order and also the probably most common used, so show it when opening the configwindow

### CODE REVIEW

**Comment by jounathaen** [comment]
OK, I wanted to make a new branch for the UI changes, but this somehow went wrong. Anyhow, some other improvements :-)

**Comment by annejan** [comment]
Will check tomorrow and might do same (Escape key) thing with the User selection screen too.

**Comment by annejan** [comment]
Solves: #142 and #84 and is a start of solving #85

**Comment by annejan** [comment]
Hahaha . .we broke Qt 4.8 compatibility . . will fix in code (instead of .ui file)

**Pull request merged**
