### PR TITLE
Moved @YoshiMan 's copy buttons inside the line Edit

### PR DESCRIPTION
**Pull request by jounathaen**
Think this looks a bit more elegant (at least on Cinnamon)
qtpass1

### CODE REVIEW

**Comment by jounathaen** [comment]
I can't test these layout changes on other window toolkits, so i'd be very interested, how this looks on Windows, Mac, KDE, etc.
Screenshots would be great :+1:

**Comment by annejan** [comment]
screen shot 2016-11-17 at 20 06 26

**Comment by YoshiMan** [comment]
My Screenshot from Antergos Linux (4.8.8-1) and Gnome (3.22.0-1)

antergoslinuxgnome

**Comment by annejan** [comment]
I think I'll merge this (in the morning) and have a look at swapping the copy button to the right.

**Comment by YoshiMan** [comment]
i think its not a good idea to move the button to the right, because you select a password on the left panel. If you place the button on the right you have to move the mouse across the whole screen.

**Pull request merged**
