### PR TITLE
Futurator redesign proper

### PR DESCRIPTION
**Pull request by annejan**
Let's do this the "github" way . .

### CODE REVIEW

**Comment by termitoz** [comment]
what I must do for chek it OK ?

**Comment by annejan** [comment]
Nothing, ignore linthub and I'll find out what went wrong with appveyour tomorrow :-)

**Comment by termitoz** [comment]
ok =)

**Comment by annejan** [comment]
There is a merge-conflict since I swapped the up (now push) and down (now pull) arrows.

**Pull request merged**
