### PR TITLE
Fix & make clearClipboard more robust

### PR DESCRIPTION
**Pull request by lukedirtwalker**
The current version had 2 bugs:
1) The clippedText was never cleared, that isn't that much of a problem
since it is overriden anyways
2) The condition to check if clearing should happen was always true
since it compared the clippedText member variable with itself. The
clippedText variables that are create above the condition are out of
scope.

I fixed these bugs and clear both clipboard types if they contain the
given text, ignoring the setting, which should make it more robust.

### CODE REVIEW

**Comment by lukedirtwalker** [comment]
I'll rebase to fix the conflicts

**Comment by lukedirtwalker** [comment]
I have some more changes I will want to commit. Should I just create a new PR? Or append here?

**Comment by annejan** [comment]
Appending here is fine by me @lukedirtwalker

**Comment by lukedirtwalker** [comment]
@annejan added some more commits, they don't really have to do with the initial fix. I think it is best to review commit by commit.

**Comment by annejan** [comment]
I will later tonight . .

**Pull request merged**
