### PR TITLE
enabled drag and drop support for passwords and passwordfolders

### PR DESCRIPTION
**Pull request by YoshiMan**
see issue #239
we are now able to move files and directories across the passwordstorage. 
e.g. 
move folder1 into folder2
move file1 into folder1
move file1 onto file2 -> opens dialog with overwrite question 
move folder1 onto file1 -> not allowed/ doesnt make sense

### CODE REVIEW

**Comment by annejan** [comment]
Selecting No in an **overwrite** dialog removes the file you were attempting to move . . 
Does feel nice (when not hitting such ^^ cases) . .

**Comment by YoshiMan** [comment]
hm. i cant reproduce. we have 3 different types. Usage with pass settings (`pass mv`) , usage with git seetings (`git mv`), and none of them (filesystem move). maybe you could attach your settings, with sensitve data stripped out.

**Comment by YoshiMan** [comment]
This pull request shouldnt be merged.
We have some wired behaviour the output of `pass mv` command is piped into the password file.... -.-
And i could reproduce your error.
I'll have to work on it.

**Comment by YoshiMan** [comment]
oooh. I know the problem @annejan described...
its a "pass" problem.
If we start the pass-script from QtPass, the pass-scripts detects, that there is no stdin (`[! -t 0]`, see http://www.tldp.org/LDP/abs/html/fto.html) and uses the force mode (`-f`) instead of interactive (`-i`).  

pass-script-excerpt
```shell
local interactive="-i"
[[ ! -t 0 || $force -eq 1 ]] && interactive="-f"
```

I'll have a look at a workaround tomorrow.

**Comment by annejan** [comment]
Wow, thank you for your hard work @YoshiMan 
This feels really nice using it . . Going to be "playing" with it for another couple of hours.

**Comment by YoshiMan** [comment]
currently its not merged correctly, because there were some merge conflicts. ill do this week, so the real testing can be done at the weekend. (hopefully the master branch stays stable ;) )

**Comment by annejan** [comment]
There will be some changes to master, at-least to try and fix #243 and #248

**Comment by annejan** [comment]
Wow . . great work on this . .
Will have some time to be able to "play" with it this evening . . 

Only other thing on my slate is currently updating the FreeBSD port ;)

**Comment by annejan** [comment]
Question (without going too deeply into the code) are files (optionally) re-encrypted if their new folder's .gpg-id options demand it?
And folders?

**Comment by annejan** [comment]
Question @YoshiMan (without going too deeply into the code) are files (optionally) re-encrypted if their new folder's .gpg-id options demand it?
And folders?

**Comment by annejan** [comment]
For me currently most user management things seem broken, might be my environment or something else, needs more investigation.
But I'm tempted to merge this work (and after that my pull request) if you want me to 😬

**Comment by YoshiMan** [comment]
@annejan. damn... they are not, if you use git settings. And with neither pass nor git, they arent reencrypted...
So it needs work again... :(
hope i can fix it tomorrow.

**Comment by annejan** [comment]
Don't worry about it :) And massive thanks on the work so-far.
I have already merged and will merge the unit testing branch as-well . .

Please open another PR when you have the re-encryption working . .

**Pull request merged**
