### PR TITLE
executeing pass show before editpassword dialog shows up

### PR DESCRIPTION
**Pull request by YoshiMan**
Double-clicking might open previous entry instead of one double-clicked on #243

### CODE REVIEW

**Comment by YoshiMan** [comment]
While working on this ticket, this `lastDecrypt` property was very confusing for me. Do we really need it?
Should it be removed? I think we could handle this with the signal/slot concept?

**Comment by annejan** [comment]
I think lastDecrypt is only used to check weather or not the clipboard should be cleared . .

We don't want to clear the clipboard if it doesn't contain the password (or something else from our app) but the user has copied something else . .

**Comment by YoshiMan** [comment]
hm. i think its the `MainWindow::clippedText`, you are talking about. This one handles the clipboard related stuff.

**Comment by annejan** [comment]
Yep .. so we could/should probably completely refactor out the lastDecrypt stuff . .

That's still a remnant from when QtPass was a simple read-only `pass` viewer for management ;)

**Comment by YoshiMan** [comment]
Alright. I'll open an Issue.

**Pull request merged**
