### PR TITLE
System Icons on Buttons and Doubleclick on treeView

### PR DESCRIPTION
**Pull request by jounathaen**
The Buttons "Add", "User", ... are now drawn with the system theme default icons and I added some spacing. (looks good on cinnamon 2.8)
Also  I added the functionality that a double-click on a item opens the edit window.
Best regards
Jonathan

### CODE REVIEW

**Comment by annejan** [comment]
I'll try this on OSX and Windows as soon as I can.
Works like a charm and looks great on KDE Arch..

**Comment by jounathaen** [comment]
Okay, i've closed the pull request as i got trouble on gnome and now my 
whole qt installation crashed. But when it works: great :-)
Best regards
Jonathan



Am 19. Dezember 2015 01:16:04 schrieb Anne Jan Brouwer 
<notifications@github.com>:

**Comment by jounathaen** [comment]
Okay, does work. Forget about the last Message

**Comment by jounathaen** [comment]
Ok, i'll keep coding some stuff until someone stops me :-D

**Comment by annejan** [comment]
Double click on folders should just open them, will fix tomorrow but won't merge to 1.6 yet.

**Comment by annejan** [comment]
Will try and merge your default buttons with some design work done by Термитоz
screen shot 2016-01-11 at 14 29 02

**Comment by annejan** [comment]
I'm going to try and cherry-pick these changes into a new branch . .

**Comment by jounathaen** [comment]
Great! the major changes would be: Icons on Buttons, Dropdown on Add Button (folder or file) and the config layout. The Icons from Термитоz look nice on KDE, I'm looking forward to see them on some other Desktop environment!

**Comment by annejan** [comment]
The problem with the graphics is that we are currently unsure about compatibility with the GPL
But the re-design (buttons to the left) of the main screen looks very good to me.

**Comment by termitoz** [comment]
I replaced the icons for free-icons + replaced progressbar for coolest animated gif. You can see the changes in my branch: https://github.com/termitoz/qtpass/tree/futurator-redesign

Also i tried to play with some warm-blacky design: https://github.com/termitoz/qtpass/tree/Futurator-redesign-warm-blacky

**Comment by annejan** [comment]
Nice!!

AJ

On 18 January 2016 23:00:56 CET, termitoz <notifications@github.com> wrote:
>I replaced the icons for free-icons + replaced progressbar for coolest
>animated gif. You can see the changes in my branch:
>https://github.com/termitoz/qtpass/tree/futurator-redesign
>
>Also i tried to play with some warm-blacky design:
>https://github.com/termitoz/qtpass/tree/Futurator-redesign-warm-blacky
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/IJHack/qtpass/pull/124#issuecomment-172665974

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by termitoz** [comment]
updated icons etc... (blue variant)

**Comment by annejan** [comment]
Merged in develop, now trying to cross-merge

**Comment by annejan** [comment]
Also TODO is detect wether or not system icons are available (not available on OSX at-least) . .

**Comment by termitoz** [comment]
New looks: 

qtpass keygen
qtpass keygen progress

**Comment by annejan** [comment]
Back on topic of this pull request . .

It looks incredibly nice on KDE 5

screenshot_20160121_031816

**Comment by annejan** [comment]
Unfortunately there are no system icons available on OSX 
screen shot 2016-01-21 at 13 26 51

Trying out on Windows next . .

**Comment by annejan** [comment]
Gnome (Fedora default)

**Comment by jsimplicio** [comment]
@annejan Not sure if you saw my post in the UI improvements PR but I made some icons for the interface. Can we use our own icons?

qtpass

**Comment by annejan** [comment]
Yes, we can @jsimplicio .  .

I am currently looking into making it easy to theme though, since I know a lot of people like to have their system-wide icon theme . . and others prefer application specific.

I'm thinking of defaulting to system-wide icons when available and when not available use our own set.

Also a possibility to change colours from system default to application specific in a simple theming way (see screenshots from @termitoz ) 

With the redesign of the configuration screen and some more changes it should be relatively easy to make a theming system, where you can simply add a folder of png's and a configuration (ini) file. . .
Kind of like WinAmp of old :dancer:

**Comment by jsimplicio** [comment]
@annejan Got ya! Anyone started trying to redesign the config screen?

**Comment by annejan** [comment]
Yes, @jsimplicio, I will add screenshots to this post when I get the chance . .
(It's available in the `develop` branch by the way . . )

**Comment by annejan** [comment]
I'm looking to replace the `stock_new-bcard` icon though, since that one is barely available . . 
http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

But can't really find a good one :cry:

**Comment by jsimplicio** [comment]
@annejan looks better. Is there anything you need some help designing for? Or making these look better ?

**Comment by annejan** [comment]
All forms of help are welcome, both in designing and just brainstorming.

For example, one thing we'll need pretty soon is to put more options into the profile's . . 
Have some ideas but they all look way complex.

Also some more stuff that was mentioned in  earlier issues.

PS. Is there a way for you to share the button set you designed  for use on OSX and Windows (set of png's or svg's would be ideal).

**Comment by jsimplicio** [comment]
@annejan Shared the icons in the UI improvements issue

**Comment by jsimplicio** [comment]
@annejan You should share your ideas for the profiles

**Comment by annejan** [comment]
@jsimplicio the discussion is in #112 git options should not be global options but maintainable per profile #112

Thanks for the round buttons, I'd really like to have "just the icons" too (as fallback for Win and OSX) for the merge of this pullrequest #124

**Comment by jsimplicio** [comment]
@annejan Sorry you were in need of those icons pretty quick. I got your email. Was just busy. Will reply back soon. :)

**Comment by annejan** [comment]
No worries :)
I'm not in need of them "that" quickly but I would love to have a new release out this weekend :smile: 

Thanks again for all the hard work . .

**Comment by jsimplicio** [comment]
@annejan By copy (password) icon do you mean a key?

**Comment by annejan** [comment]
Well, eitehr a key or a copy icon .. like .. two documents . . since that is what will be used on FreeDesktop compatible systems . .

**Comment by jsimplicio** [comment]
@annejan Ah sorry I got that confused. I was just thinking of an old message here I saw a key icon

**Pull request merged**
