### PR TITLE
refactoring - pass ifce, process mgmt

### PR DESCRIPTION
**Pull request by tezeb**
This is a first refactoring step to extract functionalities from MainWindow. It compiles and works(mostly?). I'm sharing to propose direction and gather feedback. It consist of 3 commits.
First one(e15c93f56640ef6810d3304a07fd1e0fd4bfe350) is an interface _"design"_ for _"backend"_(pass or (git/gpg...)). This was my main driver for refactoring.
Second commit(1e06efd1bdfc55a4d03d454137256b46e4389b26) moves code from MainWindow to appropriate classes. I've tried keeping changes to minimum to ease reviewing at this stage. Unfortunately, as it showed up, I had to move (probably all) process management code into my interface as well. I think it shall be further separated.
Last commit contains localization updates.

As I've already mentioned next step is extraction of process mgmt into separate class. I also think that there is a huge potential for using signal/slots mechanism for MainWindow<->Pass Interface(process mgmt) communication.

And special thx goes to @YoshiMan for extracting QtPassSettings, which was a huge help!

### CODE REVIEW

**Comment by annejan** [comment]
This sounds like exactly the kind of refactoring I was thinking about but never got the focus to do :)
Thank you very much, will look into the changes and provide feedback tomorrow.

**Comment by jounathaen** [comment]
Great, that somebody finally starts this :-)
 👍 👍 👍

**Comment by annejan** [comment]
Moved the `#ifdef __APPLE__`

In the not so wise words of me 😈 
Works on my machine .. merged!

**Comment by annejan** [comment]
According to static analysis this change even removes a identical_branches "issue" in a moc_
https://scan.coverity.com/projects/ijhack-qtpass and reduces complexity a lot . . Thanks for the effort @tezeb !!

**Comment by YoshiMan** [comment]
@tezeb awesome work. I love it. thumbs up

**Comment by tezeb** [comment]
wow, that was fast merge :) thx
Glad that you liked the changes.

@annejan regarding "housekeeping" commit, do you have some tool/config for fixing style?

**Comment by annejan** [comment]
I have set up clang default standards in vim and QtCreator . .
To fix in commandline I use `clang-format -i *.cpp *.h`

**Pull request merged**
