### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by svetlemodry**
for qtpass application

### CODE REVIEW

**Comment by annejan** [comment]
Awesome, thank you very much for the effort!

**Comment by svetlemodry** [comment]
@annejan: No probs, thanks for the quick merge!
I believe I also stumbled upon a typo in the english text - lines nr. 253+254 in `localization_en_GB.ts` file.
`... dialouge ...` => `... dialogue ...`

**Comment by annejan** [comment]
Thanks . . 
Fixed those too 😸

**Comment by annejan** [comment]
It's a typo in the actual code, copied to the translation.
Added a en_US too for those afflicted, since fixing it in code would require all translations to be fixed, that's something for another day.

**Pull request merged**
